ci/meta.yml

Fixed input name

---

resources.tf

I doubt this is correct, but it's a base

Wider iam profile

---

resources.tf

Creates a single SG encompassing all ingress and egress.

Sg creation

---

payload-test.json
resources.tf

This is a test payload for CB to create the aws-analytical cluster.  It is currently accepted but fails to create the cluster.  Pod B are investigating.
There are some obvious find and replace efforts to be done.

Added CB payload

---

generate-analytical-dataset.py

Get secrets in script

---

hive-tables-creation.py
resources.tf

removed unnecessary security group permissions that allowed all traffic. 
now only traffic goes back and forth between ADG and internal-compute

Dw 3615 security groups

---

emr-setup.sh
emr.tf
local.tf
resources.tf
terraform.tf.j2
upload_to_config_bucket.tf

Transparent encryption

---

emr-launcher.tf
emr.tf
resources.tf
upload_to_config_bucket.tf

DW-3657 - Bump EMR cluster to latest AMI to test

---

emr-launcher.tf
upload_to_config_bucket.tf

DW-3936 - Fix S3 locations

---

emr-launcher.tf

DW-3936 - Fix S3 source

---

ci/resources.yml
emr-launcher.tf
resources.tf
upload_to_config_bucket.tf

DW-3936 - Fix EMR AMI and change Secret back to data

---

resources.tf
terraform.tf.j2

DW-4007 - Fix the DKS endpoint lookup to work in preprod/prod

---

steps/hive-setup.sh

* Now that we're using the HBase API, there's no need to wait for ages for
read-replica synchronization
* EMR doesn't appear to lay down hbase-site.xml if you don't install HBase, so
instead, configure it ourselves so that it points to the ingest-hbase cluster
* Run HBase shell and hive table creation scripts as the Hadoop user; there's
no need for these to run as root

Remove read-replica related pieces from hive-tables script

---

steps/generate_analytical_dataset.py

we were previously doing: 
from datetime import datetime but we required other methods as well, so had to change to just: import datetime. 
Also added .datetime where the sub method of datetime is required 
Also sorted the python imports

Datetime fix

---

security_groups.tf

DW-3972 - Fix HBase SG rules

---

cluster_config.tf

DW-4391 - Move ADG to own subnet

---

bootstrap_actions.tf

Fixing the installer.sh proxy config

DW-4391 - Bootstrap proxy config update

---

docs/metrics.MD

Added analysis write up

---

docs/metrics.MD

Updated metrics doc after some informed feedback.

Updated metrics docs

---

steps/generate_analytical_dataset.py
steps/test_generate_analytical_dataset.py

Convert ADG Output files from parquet to Json format

DW-4544-Convert ADG Output files from  parquet to Json format

---

steps/generate_analytical_dataset.py
steps/logger.py

Ensuring JSON is valid and adding space to allow extraction of time value

Ensuring JSON is valid

---

variables.tf

Decreased number of instances in PROD to test DW-4614,

DW-4614-Investigate-missing-collections

---

bootstrap_actions.tf
bootstrap_actions/metadata.sh
cluster_config/steps.yaml.tpl
emr_jobflow_role.tf

The following intends to disable IMDSv1 on boot of then ADG EMR cluster.

Added IAM policy and bootstrap action to disable IMDSv1

---

bootstrap_actions/metadata.sh

as with concourse, I've made V2 optional.

Made v2 optional

---

ci/jobs/integration/synthetic-data-ingestion-integration.yml
ci/jobs/qa/synthetic-data-ingestion-qa.yml
ci/meta.yml

CI Pipeline migration to AWS, of synthetic dataloads.

First pass migration

---

lambda_manage_mysql_user.tf
metastore.tf
variables.tf

1. Rename lambda function to avoid naming conflict
2. Remove PDM-related SG rules as they should be managed in the PDM repo
3. Set master username back to its original, otherwise the RDS DB has to be
destroyed and recreated

Fix several deployment issues

---

metastore.tf

Reverts dwp/aws-analytical-dataset-generation#315
all tainted and reset, now to leave them ignored

Revert "Rds password"

---

local.tf
metastore.tf

DW-4967 - Bump EMR engine version for dev only

---

metastore.tf

DW-4967 - Allow cluster to apply changes immediately

---

variables.tf

increased emr version to 5.29.0

increased emr version to 5_29_0

---

local.tf

DW-4967 - Bump EMR engine for QA

---

local.tf

DW-4967 - Bump EMR engine

---

local.tf
steps.tf
steps/generate_dataset_from_htme.py
tests/test_generate_dataset_from_htme.py

DW-4896 added logic to update dynamodb audit table for success and failure scenarios with correlation_id and run_id for ADG

Dw 4896 log adg status to pipeline metadata db

---

emr_jobflow_role.tf
tests/test_generate_dataset_from_htme.py

added policy to EMR Assumerole for dynamodb

DW-4896 added policy to EMR Assumerole for dynamodb

---

steps/generate_dataset_from_htme.py

DW-5115. Fix additional hyphen issue as in agent-core_agent, it should be agent_core_agent

DW-5115. Change extra hyphen to underscore

---

steps/generate_dataset_from_htme.py

DW-5115 Fixed hyphen in file name

DW-5115 Fixed hyphen in file name

---

ci/groups.yml
ci/jobs/rotate-mysql-password-bgdc.yml
ci/meta.yml
lambda_manage_mysql_user.tf
metastore.tf
variables.tf

Create a user in Hive metastore for BGDC PoC Informatica EDC

Add a user for BGDC

---

acm.tf

DW-4790 - Enable certificate transparency logging

---

slack-alerts.tf

Tag ADG alarms so that they alerts appear in the right channels

Tag ADG alarms so that they alerts appear in the right channels

---

ci/groups.yml
ci/meta.yml

Signed-off-by: Chris Scott-Thomas <chris.scott-thomas@infinityworks.com>

Bump boto behave version

---

README.md
bootstrap_actions/metrics_config/prometheus_config.yml
cluster_config/configurations.yaml.tpl

Signed-off-by: levankirvalidze <levan.kirvalidze@dmwgroup.co.uk>

added step about downloading stuff from mvn

---

README.md

Signed-off-by: levankirvalidze <levan.kirvalidze@dmwgroup.co.uk>

added extra steps in metrics setup docs

---

ci/jobs/analytical-dataset-generation-pr.yml
ci/jobs/dev/analytical-dataset-generation-dev.yml
ci/jobs/dev/synthetic-data-ingestion-dev.yml
ci/jobs/integration/analytical-dataset-generation-integration.yml
ci/jobs/integration/synthetic-data-ingestion-integration.yml
ci/jobs/preprod/analytical-dataset-generation-preprod.yml
ci/jobs/production/analytical-dataset-generation-production.yml
ci/jobs/qa/analytical-dataset-generation-qa.yml
ci/jobs/qa/synthetic-data-ingestion-qa.yml
cluster_config.tf
tests/test_generate_dataset_from_htme.py
variables.tf

Beefy ADG without executor changes

Beefy ADG without executor changes

---

published_bucket.tf

Signed-off-by: danhill <danhill@digital.uc.dwp.gov.uk>

map common outputs until references to this repos outputs are updated

---

cluster_config.tf
cluster_config/instances.yaml.tpl
variables.tf

Use an EMR suypported type

---

ci/jobs/production/admin/start.yml
cluster_config.tf
cluster_config/configurations.yaml.tpl
variables.tf

Auto allocate memory

---

ci/jobs/production/admin/start.yml
cluster_config.tf
cluster_config/configurations.yaml.tpl
variables.tf

More memory for the executors

---

cluster_config.tf
variables.tf

Fewer cores per executor so that the memory stretches further

Fewer cores per executor so that the memory stretches further

---

ci/jobs/dev/analytical-dataset-generation-dev.yml
metastore.tf

Use new output

---

ci/jobs/dev/analytical-dataset-generation-dev.yml

Missing dev inputs

---

ci/jobs/dev/analytical-dataset-generation-dev.yml
ci/resources.yml

Missing meta

---

cluster_config.tf
security_groups.tf

Move ADG to new subnets

---

ci/jobs/dev/analytical-dataset-generation-dev.yml
ci/jobs/integration/analytical-dataset-generation-integration.yml
ci/jobs/qa/analytical-dataset-generation-qa.yml
ci/meta.yml
ci/resources.yml

Pass common output to tests

---

variables.tf

More cores and executors for ADG

More cores and executors for ADG

---

bootstrap_actions/cloudwatch.sh
cluster_config/steps.yaml.tpl
metastore.tf
steps.tf
steps/create-mongo-latest-dbs.sh

created create-mongo-latest-dbs.sh for creating dbs
Modified cloudwatch.sh added section for create-mongo-latest-dbs.log
Modified step.tf added section for create-mongo-latest-dbs
Modified steps.yaml.tpl added step for create-mongo-latest-dbs

DW 5590 Added script for creating mongo latest db

---

cluster_config/configurations.yaml.tpl
steps/generate_dataset_from_htme.py
terraform.tfvars.j2

Thread the hive tables for published tables

Thread the hive tables for published tables

---

emr_jobflow_role.tf
processed_bucket.tf

Give adg access to processed bucket as part of DW 5590
Added processed_bucket.tf
Modified emr_jobflow_role.tf to attach policy to adg role

DW-5590 Give adg access to processed bucket

---

ci/jobs/production/admin/start.yml
ci/meta.yml

Rename SNS topic

---

steps/generate_dataset_from_htme.py

Remove max worker count

---

ci/jobs/analytical-dataset-generation-pr.yml
emr-launcher.tf

Match latest launcher

---

cluster_config/cluster.yaml.tpl

Add snapshot type tag which the launcher will be populating soon

Add snapshot type tag which the launcher will be populating soon

---

steps/generate_dataset_from_htme.py

Pass the full object

---

variables.tf

Less boxes in prod so it can bring that many up

Less boxes in prod so it can bring that many up

---

ci/jobs/dev/analytical-dataset-generation-dev.yml
ci/jobs/integration/analytical-dataset-generation-integration.yml
ci/jobs/qa/analytical-dataset-generation-qa.yml

Do not terminate clusters in pipeline after the e2e

Do not terminate clusters in pipeline after the e2e

---

ci/resources.yml
cluster_config.tf
cluster_config/instances.yaml.tpl
variables.tf

Signed-off-by: Chris Scott-Thomas <chris.scott-thomas@infinityworks.com>

Set ADG instances like PDM

---

ci/resources.yml

Un pin EMR AL2 AMI

---

ci/resources.yml

Signed-off-by: Chris Scott-Thomas <chris.scott-thomas@infinityworks.com>

pin to only EMR AMIs

---

cluster_config/steps.yaml.tpl

Dw 5648 execute update contract claimant

Dw 5648 execute update contract claimant

---

processed_bucket.tf

DW-5648 fixed permission

---

cluster_config/steps.yaml.tpl

Fixed file name

---

local.tf
steps.tf
steps/send_notification.py
tests/test_send_notification.py

Suppress the notification for ADG to trigger PDM except in production

Suppress the notification for ADG to trigger PDM except in production

---

local.tf

DW-5648 increase version number

DW-5648 increase version number

---

local.tf

DW-5648 increased sql version number

DW-5648 increased sql version number

---

bootstrap_actions.tf
bootstrap_actions/cloudwatch.sh
bootstrap_actions/download_scripts.sh
bootstrap_actions/emr-setup.sh
ci/groups.yml
ci/jobs/update-pipeline.yml
ci/resources.yml
cluster_config/steps.yaml.tpl

Download the s3 files at the start of the cluster instead of halfway through to stop the pipeline affecting running clusters. Also move to self updating pipeline. `j-1QBPVMG8E940Q` cluster shows the working steps.

Download at start

---

ci/resources.yml

Remove unused resource

---

local.tf

DW-5648 increase sql version

---

ci/jobs/dev/analytical-dataset-generation-dev.yml
ci/jobs/dev/synthetic-data-ingestion-dev.yml
ci/jobs/integration/analytical-dataset-generation-integration.yml
ci/jobs/integration/synthetic-data-ingestion-integration.yml
ci/jobs/qa/analytical-dataset-generation-qa.yml
ci/jobs/qa/synthetic-data-ingestion-qa.yml
ci/meta.yml
ci/resources.yml

Update ADG pipeline to simplify test calls

Update ADG pipeline to simplify test calls

---

ci/meta.yml

Missing region var

---

ci/meta.yml

Missing source

---

cluster_config/steps.yaml.tpl
local.tf

Set cluster to terminate when finished and move steps to run before flush-pushgateway

DW-5648 update cluster setting and move steps

---

ci/jobs/dev/analytical-dataset-generation-dev.yml
ci/jobs/dev/synthetic-data-ingestion-dev.yml
ci/jobs/integration/synthetic-data-ingestion-integration.yml
ci/jobs/production/admin/start.yml
ci/jobs/qa/analytical-dataset-generation-qa.yml
ci/jobs/qa/synthetic-data-ingestion-qa.yml
ci/meta.yml
ci/resources.yml

Switch to use the new E2E repo

Switch to use the new E2E repo

---

bootstrap_actions/hive-setup.sh
ci/jobs/analytical-dataset-generation-pr.yml
ci/jobs/dev/analytical-dataset-generation-dev.yml
ci/jobs/integration/analytical-dataset-generation-integration.yml
ci/jobs/preprod/analytical-dataset-generation-preprod.yml
ci/jobs/production/analytical-dataset-generation-production.yml
ci/jobs/qa/analytical-dataset-generation-qa.yml
ci/meta.yml
ci/resources.yml
emr-relauncher.tf

Add ADG relauncher lambda

---

steps/generate_dataset_from_htme.py

Fix the location being empty at the start of the run

Fix the location being empty at the start of the run

---

bootstrap_actions/resume_step.sh
steps/generate_dataset_from_htme.py
steps/resume_step.py

Strip whitespace and rename vars to make more sense

Strip whitespace and rename vars to make more sense

---

emr-launcher.tf

added tagging iam to emr launcher

---

bootstrap_actions/cloudwatch.sh

- Abdu's work but it seems to link up with the other PR and be complete so I have raised it in his absence

Added entry to cloudwatch.sh for mongo latest

---

local.tf

Update mongo latest to v36

---

ci/jobs/analytical-dataset-generation-pr.yml

Adds shell linting via `shellcheck`

lint shell

---

bootstrap_actions/update_dynamo.sh

Remove while loop

---

local.tf

Mongo latest 40

---

cluster_config/configurations.yaml.tpl

Increase queues and parallel task count

---

bootstrap_actions/cloudwatch.sh

Signed-off-by: levankirvalidze <levan.kirvalidze@dmwgroup.co.uk>

upload e2e log file

---

bootstrap_actions.tf
bootstrap_actions/cloudwatch.sh
bootstrap_actions/emr-setup.sh
local.tf

Add missing log group for e2e testing

---

cluster_config/configurations.yaml.tpl

Wrap tez runtime value for Production only

---

emr_service_role.tf

Rename policy away from the deprecated one

Rename policy away from the deprecated one

---

cluster_config/cluster.yaml.tpl
local.tf
metastore.tf
security_groups.tf

Tag relevant recourses for use with new managed policies

Tag relevant recourses for use with new managed policies

---

emr_service_role.tf

Full access policy needed

---

emr_service_role.tf

Looks like it needs two policies now as they as scoped down

Multiple policea

---

emr_service_role.tf

Multiple policea two

---

emr_service_role.tf

Looks like it needs two policies now as they as scoped down

Looks like it needs two policies now as they as scoped down

---

cluster_config/configurations.yaml.tpl

Malformed yml

---

bootstrap_actions/hive-setup.sh

Do not stop the service

---

bootstrap_actions/hive-setup.sh

Backup queue

---

local.tf

Mongo latest v45

---

bootstrap_actions/hive-setup.sh
cluster_config/configurations.yaml.tpl
local.tf

Use capacity scheduler and switch back to mongo latest that does not specify queues to check that the tez scheduler of queues works as expected

Capacity scheduler

---

cluster_config/configurations.yaml.tpl

Remove comma

---

cluster_config/configurations.yaml.tpl

Missing quote

---

cluster_config/configurations.yaml.tpl
local.tf
variables.tf

Mongo latest 47

---

cluster_config/configurations.yaml.tpl
local.tf

Mongo latest v49 and increase things that worked more

Mongo latest v49 and increase things that worked more

---

cluster_config/configurations_incremental.yaml.tpl

Default to ORC for speedier processing of intermediate tables

Default to ORC for speedier processing of intermediate tables

---

cluster_config.tf
cluster_config/instances.yaml.tpl
variables.tf

Fix the config

---

cluster_config.tf
local.tf

Use the arn

---

cluster_config.tf
cluster_config/instances.yaml.tpl

Remove the group arn

---

cluster_config.tf
local.tf

Fix non qa prod

---

cluster_config.tf
cluster_config/instances.yaml.tpl
local.tf

Fix the usage strategy

---

cluster_config/instances.yaml.tpl

If in the reservations

---

local.tf

Mongo latest v50

---

local.tf

Quickest config we have seen so far on incremental

Quickest config we have seen so far on incremental

---

local.tf
variables.tf

Scale up preprod and removed two unused vars

Scale up preprod and removed two unused vars

---

README.md
bootstrap_actions.tf
bootstrap_actions/cloudwatch.sh
bootstrap_actions/emr-setup.sh
bootstrap_actions/status_metrics.sh
steps/courtesy-flush.sh
steps/flush-pushgateway.sh
variables.tf

adding status metrics via pushgateway

---

ci/jobs/preprod/admin/clear_dynamodb_row.yml
ci/jobs/preprod/admin/start.yml
local.tf

Use capacity reservation for Preprod and set up pipeline to run full

Use capacity reservation for Preprod and set up pipeline to run full

---

local.tf

Mongo latest v52

---

local.tf

Mongo latest v53

---

local.tf

Mongo latest v54

---

local.tf

Mongo latest v55

---

steps/generate_dataset_from_htme.py
tests/test_generate_dataset_from_htme.py

Exceptions

---

steps/generate_dataset_from_htme.py

Remove a warning and log out the prefix

Remove a warning and log out the prefix

---

ci/jobs/preprod/admin/start.yml
ci/jobs/production/admin/clear_dynamodb_row.yml

Fix preprod pipeline

---

local.tf

Mongo latest v56

---

bootstrap_actions/update_dynamo.sh

Stop the script sleeping in the time it takes an entire step to complete

Stop the script sleeping in the time it takes an entire step to complete

---

local.tf

Get notifications and alerts for preprod

Get notifications and alerts for preprod

---

cluster_config/steps.yaml.tpl
slack-alerts.tf
steps/create_pdm_trigger.py
tests/test_trigger_pdm.py

Delete old PDM rules after creating the new one to trigger

Delete old PDM rules after creating the new one to trigger

---

bootstrap_actions/cloudwatch.sh
local.tf

Update the mongo latest, fix log name and fetch new log

Update the mongo latest, fix log name and fetch new log

---

local.tf
variables.tf

Increase the number of core nodes

---

cluster_config.tf
cluster_config/instances_incremental.yaml.tpl
local.tf
variables.tf

Incremental file

---

ci/meta.yml
ci/resource_types.yml

Signed-off-by: Chris Scott-Thomas <chris.scott-thomas@infinityworks.com>

Updating container image repository

---

bootstrap_actions/cloudwatch.sh
bootstrap_actions/download_scripts.sh
local.tf

Log to mongo latest

---

bootstrap_actions.tf
bootstrap_actions/status_metrics.sh

corrected final step for status metrics

---

local.tf

Mongo latest v63

---

local.tf
variables.tf

Go back to 39 cores as it made zero difference

Go back to 39 cores as it made zero difference

---

cluster_config.tf
local.tf

Do not use capacity reservations in qa so we can remove it

Do not use capacity reservations in qa so we can remove it

---

emr_jobflow_role.tf

Missing permission for ADG

---

steps/logger.py

Fix the logging for ADG to format correctly

Fix the logging for ADG to format correctly

---

steps/generate_dataset_from_htme.py

Fix the database name so that the right one is used for incremental

Fix the database name so that the right one is used for incremental

---

ci/jobs/qa/analytical-dataset-generation-qa.yml
cluster_config.tf
emr_jobflow_role.tf
hive_metastore_connectivity.tf
security_groups.tf

Replace hive metastore SG rules

Replace hive metastore SG rules

---

bootstrap_actions.tf
local.tf
outputs.tf
private_dns.tf
steps.tf
terraform.tf.j2

More the service discovery to repo

More the service discovery to repo

---

terraform.tf.j2

Remove unused state

---

terraform.tf.j2

Signed-off-by: levankirvalidze <levankirvalidze@digital.uc.dwp.gov.uk>

point to mgt-dev when necessary for provider

---

bootstrap_actions.tf
bootstrap_actions/cloudwatch.sh
bootstrap_actions/emr-setup.sh
ci/jobs/dev/admin/start.yml
local.tf
steps/generate_dataset_from_htme.py

-add chrony log group and three log files
-enable log measurement statistics tracking in the chrony conf file
-add try/except to the function that needs detailed logs and temporarily set the boto3, botocore log level to DEBUG

Dw 6406 chrony logs

---

steps/generate_dataset_from_htme.py
tests/test_generate_dataset_from_htme.py

Thread safe s3 resource object

Thread safe s3 resource object

---

metastore.tf

Fix output

---

aviator.yml
ci/groups.yml
ci/jobs/ami-test/apply-and-test-with-ami.yml
ci/meta.yml
ci/resource_types.yml
ci/resources.yml

Dw 6496 test ami job

---

ci/jobs/ami-test/apply-and-test-with-ami.yml

Run in dir

---

bootstrap_actions/installer.sh

Signed-off-by: levankirvalidze <levankirvalidze@digital.uc.dwp.gov.uk>

remove pycryptodome to tesdt QA

---

steps/generate_dataset_from_htme.py

Signed-off-by: levankirvalidze <levankirvalidze@digital.uc.dwp.gov.uk>

expand log message

---

ci/meta.yml

Fix the duration for the pipeline

Fix the duration for the pipeline

---

README.md
ci/jobs/ami-test/apply-and-test-with-ami.yml
ci/jobs/qa/analytical-dataset-generation-qa.yml
ci/meta.yml
ci/resources.yml

* README additions
* Prevent applies running at the same time 
* Only use resources that have passed in QA
* on failure/success to track entire pipeline not just previous task/job

Dw 6496 ami test

---

ci/jobs/preprod/analytical-dataset-generation-preprod.yml

Int out of path to live to match other pipelines

Int out of path to live to match other pipelines

---

ci/jobs/ami-test/apply-and-test-with-ami.yml
ci/jobs/dev/admin/stop_incremental.yml
ci/jobs/dev/analytical-dataset-generation-dev.yml
ci/jobs/qa/analytical-dataset-generation-qa.yml
ci/meta.yml
cluster_config.tf
cluster_config/instances_incremental.yaml.tpl
variables.tf

Run full and incremental tests in parallel

Run full and incremental tests in parallel

---

emr_jobflow_role.tf
steps/create_pdm_trigger.py
tests/test_trigger_pdm.py

Remove targets from cloudwatch rules before deleting them

Remove targets from cloudwatch rules before deleting them

---

steps/create_pdm_trigger.py
tests/test_trigger_pdm.py

Fix the remove targets call

---

variables.tf

Shrink ADG incremental even more as still zero effect on the runtime

Shrink ADG incremental even more as still zero effect on the runtime

---

ci/jobs/preprod/admin/start.yml
steps/generate_dataset_from_htme.py

Change log to debug as it floods the logs

Change log to debug as it floods the logs

---

tests/test_generate_dataset_from_htme.py

Add unit test for a collection with no files in S3

Add unit test for a collection with no files in S3

---

bootstrap_actions.tf
bootstrap_actions/cloudwatch.sh
bootstrap_actions/hive-setup.sh
cluster_config.tf
cluster_config/configurations.yaml.tpl
steps.tf
steps/generate_dataset_from_historical_audit.py
steps/generate_dataset_from_historical_equality.py
tests/test_generate_dataset_from_historical_audit.py
tests/test_generate_dataset_from_historical_equality.py
tests/test_generate_dataset_from_htme.py
variables.tf

Historic equality script

---

steps/generate_dataset_from_htme.py

Add extra audit and equality logging to help debug the issue

Add extra audit and equality logging to help debug the issue

---

ci/jobs/analytical-dataset-generation-pr.yml
steps/generate_dataset_from_htme.py

Audit is not deleting the managed daily table, this is why

Audit is not deleting the managed daily table, this is why

---

steps/generate_dataset_from_historical_audit.py
steps/generate_dataset_from_historical_equality.py

Fixes for historic scripts to fix audit managed tables not deleting and add in logging that is in non historic scripts

Fixes for historic scripts to fix audit managed tables not deleting and add in logging that is in non historic scripts

---

bootstrap_actions/installer.sh
cluster_config/steps.yaml.tpl
local.tf

keeping production cluster alive

---

bootstrap_actions/installer.sh

removed pyspark install

---

steps/generate_dataset_from_historical_equality.py

correcting case on bucket name

---

bootstrap_actions/installer.sh
local.tf

This reverts commit 336b29c2c3725f8cd465637da105d8880b8869c5.

revert "keeping production cluster alive (#822)"

---

local.tf

increased driver memory and keeping cluster alive in production

---

bootstrap_actions/update_dynamo.sh
variables.tf

Check if STATE or CURRENT_STEP vars have values, if not sleep and increment count. 
If reaching max retry attempts then update Dynamo with fail state and exit 1 the script

Dw 6970 fix update dynamo.sh

---

emr-relauncher.tf

Use log level for lambdas

---

local.tf

keeping cluster alive in production for equalities import

---

local.tf

reverting production keep alive

---

local.tf

Modify non cap res region

---

local.tf

Trying a reduced memory allocation to see if this improves performance.  Larger memory allocation can cause garbage collection issues

Tweaking preprod settings, primarily reducing memory

---

local.tf

Also emending driver memory

---

bootstrap_actions.tf
bootstrap_actions/metrics-setup.sh
local.tf

updates aurora db engine version

downloads maven from s3 instead of internet
