- emr.tf
> DW-3657 - Revert bump EMR cluster to latest AMI to test

- emr.tf
> DW-3657 - Bump EMR cluster to latest AMI to test

- emr/adg/cluster.yaml.tpl
- emr/adg/configurations.yaml.tpl
- local.tf
AWS have advised that we don't need EMRFS configured at all for an HBase
read-replica.
In addition, because QA's ingest-hbase cluster is breaking, disable ADG in
that environment for now as it's blocking pipelines reaching production.
> DW-4048: Disable EMRFS + QA

- cluster_config.tf
Yes, really! Java uses a pipe-separated list, not a comma separated list.
https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html
> Delimit Spark no_proxy settings with pipes

- local.tf
PySpark is using virtual-host style requests for S3 access, so route all
requests to <bucket_name>.s3.<region>.amazonaws.com as well as
s3.<region>.amazonaws.com through the S3 endpoint, not the proxy.
> Bypass proxy for all region-based S3 requests

- local.tf
Ensure that ADG and analytical-Env always use the same EMP, to do this it was decided that the jar name will always be encryption-materials-provider-all.jar and changes will over write the existing jar and result in new jar with same name.
Removed emp_version from local.tf.
replaced /encryption-materials provider-${local.emp_version[local.environment]}.jar
with /encryption-materials-provider-all.jar in local.tf
> DW-4330 Removed version from EMP in local.tf

- local.tf
This sets every environment to run at
1 minute past midnight of every day of every month of every year regardless of the day-of-week of every year
With the exception of Production which we're not quite ready to switch on yet.
> Correct the Lambda CloudWatch Cron Schedule

- cluster_config.tf
- cluster_config/instances.yaml.tpl
When multiple EC2 subnet IDs are specified, Amazon EMR evaluates them and launches
instances in the optimal subnet. This will help ADG be robust against an AZ failure
at launch time.
(https://docs.aws.amazon.com/emr/latest/APIReference/API_JobFlowInstancesConfig.html#EMR-Type-JobFlowInstancesConfig-Ec2SubnetIds)
> Specify multiple subnets for the ADG cluster

- bootstrap_actions.tf
> DW-4391 - Fixing proxy ref in emr-setup.sh script to be ECS rather than EC2 proxy

- published_bucket.tf
The custom key policy is the same as the default key policy so can be removed.
> Remove custom key policy from published bucket CMK

- local.tf
Schedule ADG run on Integration environment after changing the parameters of AWS-Ingest spec to match with Prod.
> Schedule ADG run on Integration environment 

- published_bucket.tf
- variables.tf
* The policy analytical_dataset_crown_read_only had been incorrectly linked to the analytical_dataset_read_only document meaning that it wasn't being restricted by the crown tag, as intended.
* There needs to be a policy to restrict access to PII data on the condition of another tag. I have set up a boolean tag as follows: `Pii: <value>`
> correcting policy attached to analytical_dataset_crown_read_only and adding non_pii policy

- cluster_config.tf
- cluster_config/instances.yaml.tpl
- variables.tf
Setting the ADG instances to use  weighted capacity in case where the instances are not provisioned by AWS ( Throws ""Provisioning for instance fleet timed out" error)
> Setting-adg-weighted-capacity

- aviator.yml
- ci/groups.yml
- ci/jobs/dev/admin/start.yml
- ci/jobs/dev/admin/stop.yml
There's no reason being able to stop and start clusters in Dev shouldn't exist in the pipeline.
> No reason this shouldn't exist

- variables.tf
This scales prod down so that it'll create a maximum of 26x m5.12xlarge instances,
which will entirely consume a /27 subnet (/27 = 32 IPs, -5 for internal AWS use, -1 for EMR service use).
> Reduce prod scale

- variables.tf
This gives it room for 1 master + 1 EMR service IP to fill the /27 subnet
> Drop prod to 25 core nodes

- cluster_config.tf
- cluster_config/cluster.yaml.tpl
- cluster_config/configurations.yaml.tpl
- variables.tf
We are hitting memory issues when serializing larger collections, so try using the Kyro serializer instead. From https://aws.amazon.com/blogs/big-data/best-practices-for-successfully-managing-memory-for-apache-spark-applications-on-amazon-emr/
> Upgrade to EMR-5.29.0 and use the Kyro Serializer

- published_bucket.tf
* The Analytical Environment requires permission to read files from the aws-analytical-env-metrics-data folder in the published bucket - this is where we are storing standardised dummy data for performance measuring.
> [DW-4712] Add permission to read from performance metrics data folder in s3

- ci/meta.yml
- security_groups.tf
The lambda needs to communicate to RDS via port 443 not 3306 as this is a HTTPS request and not a mysql command. 
The lambda also needs access to vpc endpoints where RDS lives. 
I was also calling the lambda with the wrong name previously.
> changing and adding new SG rules for lambda

- ci/groups.yml
- ci/jobs/rotate-mysql-password-adg-reader.yml
- lambda_manage_mysql_user.tf
the previous root-ca was for a Serverless implementation. this one is necessary for the currently deployed RDS Aurora instance. 
also, removed adg-reader user from production environment. This user is not required and is only available currently for testing out what adg wrote into the database. Therefore there is no reason for it to go to prod.
> change root ca as previous one was for a serverless implementation

- cluster_config.tf
- cluster_config/configurations.yaml.tpl
- local.tf
This allows each environment to choose whether or not to
use Aurora or Glue as the metastore backend to support seamless
migrations.
> Make Hive database backend configurable per env

- ci/jobs/production/analytical-dataset-generation-production.yml
None of our infra is ready to work with the new version of the
Lambda, so pin it back to a previous version for now.
> Revert EMR launcher Lambda release that breaks production

- cluster_config.tf
- metastore.tf
The access was only required to get at the secret_version's
id, which can be got from the secret directly.
> Remove admin access to RDS secret value

- bootstrap_actions/emr-setup.sh
This is installed on our custom AMIs but not on AWS' generic AMI.
> Temporarily install ACM retriever utility

- bootstrap_actions.tf
- bootstrap_actions/emr-setup.sh
Also, stop installing certificates outside of a JKS as it appears
to not work under Python-3.7 and nothing outside of Java need those
certificates.
> Use sudo to install Python packages

- local.tf
- metastore.tf
This adds support for shipping MySQL logs from the Hive Metastore
cluster to CloudWatch. It also enables Peformance Insights so we
can get visibility of potential performance issues.
Finally, it adds supporting infra to enable Enhanced Monitoring
should the above tools hint that it would provide value. As we
don't yet know whether it's valuable, or at what frequency we should
collect metrics, it's simply disabled for now, but easily enabled
on a per-env basis.
> DW-5094: Hive Metastore CloudWatch Logs and Insights

- metastore.tf
None of our other CloudWatch log groups appear to be encrypted with KMS
so remove it from here. Also fix a typo in the RDS parameter group.
> DW-5094: Remove log encryption

- metastore.tf
Enhanced monitoring config isn't optional; if you specify a role
you must provide a non-0 value for the monitoring period.
> DW-5094: Remove enhanced monitoring config

- local.tf
- metastore.tf
Performance Insights can't be enabled on T-Class instances (see
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.Overview.html#USER_PerfInsights.Overview.Engines).
So, make Perf Insights configurable per environment and only enable
in Production for now.
> DW-5094: Allow Performance Insights to be configurable per env

- metastore.tf
The `log_output` parameter is set to FILE by default and specifying it
explicitly causes Terraform to detect a perpetual diff in configs.
> DW-5904: Remove log_output parameter

- metastore.tf
1. Plans are diverging because AWS' docs are rubbish.
2. Ensure CloudWatch log groups exist before the DB cluster comes up, otherwise
the cluster creates them, meaning Terraform can't.
> DW-5904: Fix diverging plans

- local.tf
- metastore.tf
This ensures we have at least one other env with the
same config as prod.
Also, export the error logs to CloudWatch. The docs say that they're
exported by default, but if you choose to export some non-default logs
then that overrides *that* default so they end up *not* being exported.
> DW-5904: Enable performance insights in QA

- steps/generate_dataset_from_htme.py
- tests/test_generate_dataset_from_htme.py
This is done with the aims of:
1. Reducing S3 spend by compressing the 17TB of ADG data (prod)
2. Speeding up PDM by not having to perform I/O on 17TB of ADG data
> DW-5281: Compress ADG output

- metastore.tf
No longer needed as:
* Versions are created by CI rotate jobs
* Terraform doesn't (and shouldn't) consume secret versions, only secret itself
> Remove the resource as no longer needed

- ci/groups.yml
- ci/jobs/rotate-mysql-password-kickstart-adg.yml
- ci/meta.yml
- lambda_manage_mysql_user.tf
- metastore.tf
- variables.tf
Hello,
This change is for adding new user for kickstart adg process which will have write access on hive metastore RDS mysql instance. As per this change following files has been altered
1. variables.tf -> add new variable with username for kickstart adg process
2. metastore.tf -> add new resource to create secret manager which stores metastore kickstart adg process
3. lambda_manage_mysql_user.tf -> updated the lambda role policy document to allow access to new secrets manager for kickstart
4. meta.yml -> add new plan for rotating mysql password for kickstart adg process
5. rotate-mysql-password-kickstart-adg.yml --> This is the new file stores plan for all environment
Requesting you to review and let me know in case of any concern
Thanks and Regards
Ashis Prasad
> byuc-271_Add new mysql user for kickstart adg process

- cluster_config.tf
- cluster_config/configurations.yaml.tpl
- emr_jobflow_role.tf
- local.tf
- variables.tf
Use m5.16xlarge instead as there are no 24xlarges left in the AZs
> Use m5.16xlarge instead as there are no 24xlarges left in the AZs

- cluster_config/steps.yaml.tpl
We need to flush at the start and at the end of a run.  When the cluster job fails, it does not clear down the pushgateway and leaves messy, and confusing metrics.
> Add flush at start to ensure pushgateway is always cleared

- steps/flush-pushgateway.sh
Now we flush before and after running, the five minute sleep timer is excessive.  Scrape intervals are every 60 seconds, and scrape timeouts are 10 seconds.  This should suitably cover the final window, without costing too much time at either end of the run.
> Reduce wait to a suitable window

- cluster_config/steps.yaml.tpl
- steps.tf
- steps/courtesy-flush.sh
- steps/flush-pushgateway.sh
75s appears to have not been a long enough wait to collect the final metrics, increased to 3 mins.  
We should not have to wait at all at the start, so the two steps needed to be split.
> Flush wait flush

- bootstrap_actions.tf
- bootstrap_actions/cloudwatch.sh
- bootstrap_actions/emr-setup.sh
- bootstrap_actions/update_dynamo.sh
- ci/jobs/dev/admin/start.yml
- ci/jobs/dev/analytical-dataset-generation-dev.yml
- ci/jobs/integration/admin/start.yml
- ci/jobs/preprod/admin/start.yml
- ci/jobs/production/admin/start.yml
- ci/jobs/qa/admin/start.yml
- ci/meta.yml
- ci/resources.yml
- cluster_config/cluster.yaml.tpl
- cluster_config/steps.yaml.tpl
- emr_jobflow_role.tf
- local.tf
- pdm_emr_launcher.tf
- slack-alerts.tf
- steps.tf
- steps/courtesy-flush.sh
- steps/create_pdm_trigger.py
- steps/generate_dataset_from_htme.py
- steps/send_notification.py
- tests/test_generate_dataset_from_htme.py
- tests/test_send_notification.py
- tests/test_trigger_pdm.py
Generate the cloudwatch rule and target to trigger PDM via an ADG step, not hardcoded in TF. To do this, need to use the export date which is now passed through to ADG so need to work out the cut offs incase retries for ADG go past the midnight boundary.
Do not trigger PDM if:
1. Setting passed in to skip (for lower envs)
2. Time is past 3am on the day AFTER the export date (i.e. running in to the next day's runs)
If time is before 3pm on day of export, then generate a cloudwatch rule to trigger PDM at 3pm that day.
If time is after 3pm on day of export, then generate a cloudwatch rule to trigger PDM 5 minutes from now.
The dynamo db table's date field switched to have the export date, not the date of run as this is what matters. Also pass this through to PDM so it can use it too.
This …
> Trigger pdm

- cluster_config.tf
- cluster_config/steps.yaml.tpl
- local.tf
In lower env only run executeUpdateStatement scripts as that is the only one we have tests built for and the only one where we have the required data.
> run updatestatement script in lower envs

- cluster_config/configurations.yaml.tpl
Number of Tez containers are limited by available memory of core worker due to Tez default memory limit.
> Increase the number of Tez containers per core node by reducing mem res

- steps/create_pdm_trigger.py
- tests/test_trigger_pdm.py
Fix the PDM trigger where currently if ADG finishes right on the cut off time, by the time the CW event is created, it is too late to trigger, so create the trigger with 5 minutes in the future so there is always a small gap
> Fix trigger

- bootstrap_actions.tf
Marks ADG as complete for status metrics, when `spark-submit` job is complete.  For service dashboard etc, we shouldn't care that anything after this step failed.
> mark ADG as complete when spark-submit is successful

- emr_jobflow_role.tf
Fix permissions for deleting expired cloudwatch PDM rules
> Fix permissions for deleting expired cloudwatch PDM rules

- ci/jobs/ami-test/apply-and-test-with-ami.yml
- ci/meta.yml
* Triggering from same resources as deployment pipeline
* Input for each task
* Source exit script in each task (if input is present)
* Task to check if AMI id already passed the tests
I did it this way as it seems to keep most of the logic in the test job/new task. Seems like the best solution without over complicating it.
> adding job to check success with current AMI and using output to exit steps

- tests/test_generate_dataset_from_htme.py
Reinsert double processing in data tests to ensure tthat overwriting works correctly
> Reinsert double processing in data tests to ensure tthat overwriting works correctly

- emr-launcher.tf
- local.tf
Do not schedule ADG in environmnents via the lambda as not used anymore
> Do not schedule ADG in environmnents via the lambda as not used anymore
